name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-venv \
            autoconf automake libtool \
            pkg-config zlib1g-dev libffi-dev \
            libssl-dev

      - name: Instalar Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython

      - name: Aceitar licencas Android
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Instalar Android SDK necessario
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;37.0.0"

      - name: Compilar APK
        env:
          ANDROIDSDK: ${{ env.ANDROID_HOME }}
        run: |
          buildozer -v android debug

      - name: Localizar APK
        run: |
          find bin -type f -name "*.apk" -print

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: Crypto-Certified-Switch-APK
          path: bin/*.apk
          if-no-files-found: error
